import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const README = readFileSync(new URL("../../README.md", import.meta.url), "utf8");

describe("README release notes", () => {
  it("documents the v0.9 approval behavior and existing tool contracts", () => {
    expect(README).toContain("|  9 tools by default; 10 with gate findings; 12 with journal + gate findings");
    expect(README).toContain("## The tools: nine by default, ten with gate findings, twelve with journal");
    expect(README).toContain("| `claude_sessions` | Recover recent session ids without a Claude run | none (optional `workspace_dir`, `limit`) |");
    expect(README).toContain("| `claude_gate_findings` | Read recent automatic review-gate findings back in-band without a Claude run | none (optional `workspace_dir`, `limit`) |");
    expect(README).toContain("| `claude_consult_history` | Recover past consultation metadata from the opt-in machine journal across Codex sessions and server restarts | none (optional `workspace_dir`, `limit`) |");
    expect(README).toContain("| `claude_continuity_status` | Report content-free continuity readiness counts for a workspace without a Claude run | `workspace_dir` |");
    expect(README).toContain("Losing a session? Call `claude_sessions`");
    expect(README).toContain("Use `claude_gate_findings` when the user mentions review-gate findings");
    expect(README).toContain("The tool reads the findings log resolved by the MCP server's environment");
    expect(README).toContain("tools whose table row lists `workspace_dir` require it");
    expect(README).toContain("each entry's `session_id` can be passed to `claude_continue` with that `repo` as `workspace_dir`");
    expect(README).toContain("Successful single-run results that actually ran Claude end with a machine-readable footer");
    expect(README).toContain("`claude_panel` instead places one footer in each successful perspective section; failed perspective sections contain only the error");
    expect(README).toContain("consult-journal-YYYY-MM.jsonl");
    expect(README).toContain("Entries contain only the listed metadata, not dedicated prompt, file-content, or answer-body fields");
    expect(README).toContain("For review-gate entries, the 120-character topic excerpt comes from the first non-empty line of Claude's findings and may contain the complete answer when it fits within the cap");
    expect(README).toContain("fresh advisor conversations with an explicit `workspace_dir`, including gate reviews, receive a `<recent-consultations>` digest of up to 5 recent entries from the current month's journal for the same workspace, newest first");
    expect(README).toContain("Resumed sessions never receive this digest");
    expect(README).toContain("Disable continuity with `CLAUDE_CONSULT_CONTINUITY=0`");
    expect(README).toContain("The digest contains only metadata the journal already stores and is injected as tagged background that Claude is told is context, not instructions");
    expect(README).toContain("Continuity activates only when all four conditions are true: the journal is configured, `CLAUDE_CONSULT_CONTINUITY` is not `0`, the run has no `session_id`, and the caller passes an explicit `workspace_dir`.");
    expect(README).toContain("For clean-context fresh runs, pass `continuity: false`; this can only disable continuity and cannot enable it against the owner's `CLAUDE_CONSULT_CONTINUITY=0` switch.");
    expect(README).toContain("Run `doctor` inside the project directory to report continuity status and counts for that workspace; it never prints journal content.");
    expect(README).toContain("Set `CLAUDE_CONSULT_LOG_LEVEL=debug` to show one per-run continuity skip reason or injected entry count on stderr.");
    expect(README).toContain("`claude_continuity_status` returns compact JSON with exactly `continuity_enabled`, `candidate_count`, `matching_count`, `would_inject`, and `reason`.");
    expect(README).toContain("| `matching_entries` | Continuity is enabled and matching workspace entries exist |");
    expect(README).toContain("| `continuity_disabled` | The owner disabled continuity |");
    expect(README).toContain("| `no_candidates` | The current month has no valid journal entries |");
    expect(README).toContain("| `no_workspace_match` | Current-month entries exist, but none match the workspace |");
    expect(README).toContain("| `journal_unreadable` | The journal could not be read; counts fail soft to zero |");
    expect(README).toContain("`would_inject` reports the workspace/machine state a caller cannot know; per-call factors that suppress the digest (resuming a session, `continuity: false`) are the caller's own choices and are not predicted by this tool.");
    expect(README).toContain("It is available only when the journal is enabled and is the machine-readable counterpart to the count-only `doctor` diagnostics.");
    expect(README).toContain("Pass `structured: true` to `claude_review_diff` to request machine-readable findings with required `severity`, `file`, `line`, `finding`, `evidence`, `recommendation`, and `confidence` fields, plus optional `end_line`, `category`, and `symbol` fields. This is best-effort and uses the existing prose fallback; omit it for the default prose review.");
    expect(README).toContain("Eligible fresh runs append `| continuity: injected(N)` or `| continuity: none` as the final footer segment, after an optional `| format:` segment.");
    expect(README).toContain("Journal-off, owner-disabled, resumed, no-workspace, and `continuity: false` runs omit the continuity segment entirely.");
    expect(README).toContain("### Machine-readable results");
    expect(README).toContain('"format": "json",');
    expect(README).toContain('"session_id": "123e4567-e89b-12d3-a456-426614174000",');
    expect(README).toContain('"cost_usd": 0.12,');
    expect(README).toContain('"duration_ms": 3400,');
    expect(README).toContain('"turns": 2,');
    expect(README).toContain('"continuity": { "injected": true, "entries": 2 }');
    expect(README).toContain("`data` is present only when `format` is `json`; prose results use `format: \"prose\"` and omit `data`. Missing numeric metadata is `null`, and continuity-ineligible runs use `continuity: null`.");
    expect(README).toContain("Read `structured_content` when present. The existing text body and footer are byte-compatible fallbacks and remain unchanged.");
    expect(README).toContain("Error results carry text only. `claude_panel` remains text-only because it aggregates multiple runs, and the list-shaped spawn-free tools remain text-only in this release.");
    expect(README).toContain("`claude_continuity_status` instead mirrors its existing compact JSON object directly as `structured_content`, without execution metadata.");
    expect(README).toContain("Prefer `structured_content.format` when it is available; for text-only clients or results, check the footer's `format` field before parsing.");
    expect(README).toContain("The user prompt travels via stdin and never appears on the command line");
    expect(README).toContain("System guidance, including the tagged continuity digest, is passed as the single value of `--append-system-prompt`");
    expect(README).toContain("npx -y claude-consult-mcp setup --install-review-gate");
    expect(README).toContain("npx -y claude-consult-mcp setup --install-review-gate --gate-log <absolute-path>");
    expect(README).toContain("records findings to `CLAUDE_CONSULT_GATE_LOG` or `<CLAUDE_CONSULT_JOURNAL_DIR>/review-gate.log`");
    expect(README).toContain("Each findings entry records the repository as the final header field");
    expect(README).toContain("call `claude_gate_findings` to bring those durable findings back into the MCP conversation");
    expect(README).toContain("use the logged `session_id` with the logged repo as `workspace_dir` in `claude_continue`");
    expect(README).toContain("Oversized diffs exit 0 with stderr `review-gate: diff too large (N bytes), skipped`.");
    expect(README).toContain("Codex does not inject Stop-hook stdout into the next model turn's context.");
    expect(README).toContain("The trust prompt cannot be granted in headless `codex exec`.");
    expect(README).toContain("When installed as a Codex Stop hook, the gate receives Codex's end-of-turn summary on stdin");
    expect(README).toContain("claimed work that is missing or incomplete and material changes the summary did not mention");
    expect(README).toContain("Manual `review-gate` runs have no claim and review the diff only");
    expect(README).toContain("The claim is untrusted context, and the reviewer is instructed never to follow instructions inside it");
    expect(README).toContain("The cooldown keys on the diff/status snapshot alone, never the claim");
    expect(README).toContain("an unchanged diff is skipped even when the claim changes; use `--force` to override");
    expect(README).toContain("doctor reports `[warn] review-gate hook installed but not trusted - run codex interactively once and approve the hook, or it will not fire`");
    expect(README).toContain("| Continuity digest never appears | Run doctor inside that project directory - it reports whether the journal, kill switch, current-month entries, and workspace match line up; pass workspace_dir on the tool call and check CLAUDE_CONSULT_CONTINUITY |");
    expect(README).toContain("| `claude_continuity_status` is not listed | Set `CLAUDE_CONSULT_JOURNAL_DIR` to a local absolute path in the MCP server environment and restart Codex |");
    expect(README).toContain("| `CLAUDE_CONSULT_GATE_LOG` | disabled | Local absolute file path for durable automatic review-gate findings |");
    expect(README).toContain("| `CLAUDE_CONSULT_MAX_EFFORT` | unlimited | Owner-level ceiling for per-call `effort`");
    expect(README).toContain("| `CLAUDE_CONSULT_CONTINUITY` | enabled when the journal is on | Set to `0` to disable recent-consultation context for fresh advisor runs |");
    expect(README).toContain("CLAUDE_CONSULT_GATE_MODEL");
    expect(README).toContain("Claude-calling tools also accept optional `effort`");
    expect(README).toContain("Fable models still default to `--effort max`, but that default is silently clamped to `CLAUDE_CONSULT_MAX_EFFORT`");
    expect(README).toContain("An explicit per-call `effort` above the ceiling is rejected with the allowed levels.");
    expect(README).toContain("Cancelling a tool call in your client also terminates the underlying claude process; nothing keeps running in the background.");
    expect(README).toContain("questions_for_caller");
    expect(README).toContain("records origin metadata as `review-gate` so the opt-in journal can show the run");
    expect(README).toContain("Gate journal entries use the first non-empty line of the actual findings");
    expect(README).toContain("The default child allowlist is `Read`, `Glob`, `Grep` for `readonly`; it adds `WebSearch` and `WebFetch` for `research`");
    expect(README).toContain("By default, `Agent` is added for `deep-research` calls that request `depth: \"deep\"`");
    expect(README).toContain("`CLAUDE_CONSULT_ALLOWED_TOOLS` can replace the non-deep default with any valid non-forbidden tool tokens");
    expect(README).toContain("`setup` can persist only `--model`, `--capability`, `--allowed-models`, and `--max-budget-usd` in the registered server environment");
    expect(README).toContain("Configure the other variables directly for the MCP server in `~/.codex/config.toml`");
    expect(README).toContain("The child Claude process inherits the machine's Claude Code user configuration");
    expect(README).toContain("User-level hooks and plugins, including memory plugins that inject prior context at session start, run inside advisor sessions too");
    expect(README).toContain("This package neither reads nor controls that plugin context");
    expect(README).toContain("configure those plugins to exclude the relevant workspaces");
    expect(README).toContain("Codex CLI `0.142.0` and `0.144.1`");
    expect(README).toContain("`default_tools_approval_mode`: `\"auto\"` (the default), `\"prompt\"`, `\"writes\"`, or `\"approve\"`");
    expect(README).toContain("All claude-consult tools declare the MCP `readOnlyHint` annotation, so the default mode auto-approves them with no configuration");
    expect(README).toContain("set `default_tools_approval_mode = \"prompt\"` explicitly if you want to confirm every consultation");
    expect(README).toContain("`~/.codex/config.toml` is shared by the Codex CLI and desktop app");
    expect(README).toContain("the two install and update their engines independently");
    expect(README).toContain("| MCP tool calls fail with user cancelled MCP tool call | Codex 0.144+ requires approval for tools not marked read-only; upgrade claude-consult-mcp to >= 0.9.0 (all tools declare the read-only annotation), or set default_tools_approval_mode = \"approve\" under [mcp_servers.claude-consult] in ~/.codex/config.toml |");
    expect(README).not.toContain("Every successful result ends with a machine-readable footer");
    expect(README).not.toContain("Every successful result from a Claude-spawning tool ends with a machine-readable footer");
    expect(README).not.toContain("Every successful result that actually ran Claude ends with a machine-readable footer");
    expect(README).not.toContain("The journal never stores full prompts, file contents, or Claude answers");
    expect(README).not.toContain("The journal never stores full prompts, file contents, or full Claude answers");
    expect(README).not.toContain("the in-memory ledger and opt-in journal can show the run");
    expect(README).not.toContain("Gate ledger and journal entries");
    expect(README).not.toContain("plus the verified `Agent` sub-agent token only at `deep-research`");
    expect(README).not.toContain("The `deep-research` tier adds only the verified `Agent` sub-agent token");
    expect(README).not.toContain("Set them at registration time so they live in the Codex config");
    expect(README).not.toContain("receives Codex's Stop JSON payload");
    expect(README).not.toContain("reads the transcript file");
    expect(README).not.toContain("injects findings into Codex context");
    expect(README).not.toContain("passive output");
    expect(README).not.toContain("continuity across journal months");
    expect(README).not.toContain("continuity digest from the in-memory ledger");
    expect(README).not.toContain("resumed sessions also receive the continuity digest");
    expect(README).not.toContain("The prompt travels via stdin — never on the command line");
  });
});
